import { NextRequest, NextResponse } from 'next/server'
import { createSupabaseAdmin } from '@/lib/supabase'
import { requireAuth, requirePermission, unauthorizedResponse } from '@/lib/api-auth'
import { canAccessBranch, resolveCompanyId } from '@/lib/tenant'
import { createCashAuditLog, getOpenCashRegister, mapPaymentMethodToCashMethod } from '@/lib/cash'

export const dynamic = 'force-dynamic'

async function resolveScopedAppointmentIds(input: {
  supabase: ReturnType<typeof createSupabaseAdmin>
  auth: Awaited<ReturnType<typeof requireAuth>>
  companyId: string | null
  branchId?: string | null
}) {
  const { supabase, auth, companyId, branchId } = input

  let query = supabase
    .from('appointments')
    .select('id')

  if (companyId) {
    query = query.eq('company_id', companyId)
  }

  if (branchId) {
    query = query.eq('branch_id', branchId)
  }

  if (auth?.role !== 'superadmin' && auth?.branch_ids.length && !branchId) {
    query = query.in('branch_id', auth.branch_ids)
  }

  if (auth?.role === 'barber') {
    if (!auth.barber_id) return []
    query = query.eq('barber_id', auth.barber_id)
  }

  const { data } = await query
  return (data ?? []).map((appointment: { id: string }) => appointment.id)
}

export async function POST(req: NextRequest) {
  const auth = await requireAuth(req)
  if (!auth) return unauthorizedResponse()
  const denied = requirePermission(auth, 'cash.add_movement')
  if (denied) return denied

  const body = await req.json().catch(() => null)
  if (!body) return NextResponse.json({ error: 'Body inválido' }, { status: 400 })
  const { appointment_id, amount, method, notes } = body

  if (!appointment_id || !amount || !method) {
    return NextResponse.json({ error: 'Faltan datos del pago' }, { status: 400 })
  }

  const parsedAmount = Number(amount)
  if (!Number.isFinite(parsedAmount) || parsedAmount <= 0) {
    return NextResponse.json({ error: 'El monto debe ser mayor a 0' }, { status: 400 })
  }

  const validMethods = ['efectivo', 'mercado_pago', 'debito', 'transferencia']
  if (!validMethods.includes(method)) {
    return NextResponse.json({ error: 'Método de pago inválido' }, { status: 400 })
  }

  const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i
  if (!UUID_RE.test(appointment_id)) {
    return NextResponse.json({ error: 'ID de turno inválido' }, { status: 400 })
  }

  const supabase = createSupabaseAdmin()
  const companyId = auth.role === 'superadmin' ? null : await resolveCompanyId(auth, supabase)
  let appointmentQuery = supabase
    .from('appointments')
    .select('id, barber_id, branch_id, service_id, company_id, service_price, service:services(price)')
    .eq('id', appointment_id)

  if (companyId) {
    appointmentQuery = appointmentQuery.eq('company_id', companyId)
  }

  const { data: appointment } = await appointmentQuery.maybeSingle()

  if (!appointment) {
    return NextResponse.json({ error: 'Turno no encontrado' }, { status: 404 })
  }
  const expectedAmount = Number(appointment.service_price ?? (appointment.service as any)?.price ?? 0)
  if (expectedAmount > 0 && Math.abs(parsedAmount - expectedAmount) >= 0.01) {
    return NextResponse.json({
      error: `El monto debe coincidir con el precio de la sucursal: ${expectedAmount}`,
    }, { status: 400 })
  }

  if (auth.role === 'barber' && appointment.barber_id !== auth.barber_id) {
    return NextResponse.json({ error: 'No tenés permisos para registrar este cobro' }, { status: 403 })
  }

  if (!appointment.branch_id) {
    return NextResponse.json({ error: 'El turno no tiene sucursal asignada' }, { status: 400 })
  }

  if (auth.role !== 'superadmin') {
    const allowed = await canAccessBranch(auth, supabase, appointment.branch_id)
    if (!allowed) {
      return NextResponse.json({ error: 'No tenés acceso a la sucursal de este cobro' }, { status: 403 })
    }
  }

  const openRegister = await getOpenCashRegister(supabase, appointment.branch_id)
  if (!openRegister) {
    return NextResponse.json({ error: 'No hay una caja abierta en esta sucursal' }, { status: 409 })
  }

  const effectiveCompanyId = companyId ?? appointment.company_id ?? openRegister.company_id ?? null
  if (!effectiveCompanyId) {
    return NextResponse.json({ error: 'El turno no tiene empresa asignada' }, { status: 400 })
  }

  if (openRegister.company_id && openRegister.company_id !== effectiveCompanyId) {
    return NextResponse.json({ error: 'La caja abierta pertenece a otra empresa' }, { status: 409 })
  }

  let existingPaymentQuery = supabase
    .from('payments')
    .select('id, amount, method, receipt_number')
    .eq('appointment_id', appointment_id)

  existingPaymentQuery = existingPaymentQuery.eq('company_id', effectiveCompanyId)

  const { data: existingPayment } = await existingPaymentQuery.maybeSingle()

  if (existingPayment) {
    return NextResponse.json({ payment: existingPayment })
  }

  // Create payment (receipt_number auto-generated by DB trigger)
  const { data, error } = await supabase
    .from('payments')
    .insert({
      appointment_id,
      company_id: effectiveCompanyId,
      amount: parsedAmount,
      method,
      notes: notes ?? null,
      created_by: auth.session.user.id,
    })
    .select('*')
    .single()

  if (error) return NextResponse.json({ error: error.message }, { status: 500 })

  const { data: movement, error: movementError } = await supabase
    .from('cash_movements')
    .insert({
      cash_register_id: openRegister.id,
      company_id: openRegister.company_id,
      branch_id: openRegister.branch_id,
      type: 'income_service',
      payment_method: mapPaymentMethodToCashMethod(method),
      amount: parsedAmount,
      description: 'Cobro de servicio',
      reference_type: 'payment',
      reference_id: data.id,
      created_by_user_id: auth.session.user.id,
    })
    .select('id')
    .single()

  if (movementError) {
    await supabase.from('payments').delete().eq('id', data.id).eq('company_id', data.company_id)
    return NextResponse.json({ error: movementError.message }, { status: 500 })
  }

  // Mark appointment as completed only after the payment exists.
  const { error: apptError } = await supabase
    .from('appointments')
    .update({ status: 'completada' })
    .eq('id', appointment_id)
    .eq('company_id', effectiveCompanyId)

  if (apptError) {
    return NextResponse.json({ error: apptError.message }, { status: 500 })
  }

  await createCashAuditLog(supabase, {
    company_id: openRegister.company_id,
    branch_id: openRegister.branch_id,
    cash_register_id: openRegister.id,
    action: 'cash_register.service_payment_recorded',
    entity_type: 'payment',
    entity_id: data.id,
    performed_by_user_id: auth.session.user.id,
    metadata: {
      appointment_id,
      movement_id: movement.id,
      amount: Number(amount),
      payment_method: method,
    },
  })

  return NextResponse.json({ payment: data })
}

export async function GET(req: NextRequest) {
  const auth = await requireAuth(req)
  if (!auth) return unauthorizedResponse()
  const denied = requirePermission(auth, 'cash.view')
  if (denied) return denied

  const { searchParams } = new URL(req.url)
  const branch_id  = searchParams.get('branch_id')
  const date_from  = searchParams.get('date_from')
  const date_to    = searchParams.get('date_to')

  const supabase = createSupabaseAdmin()

  // Scope to caller's company at DB level — no cross-tenant leakage
  const companyId = auth.role === 'superadmin'
    ? null
    : await resolveCompanyId(auth, supabase)
  if (branch_id && auth.role !== 'superadmin') {
    const allowed = await canAccessBranch(auth, supabase, branch_id)
    if (!allowed) {
      return NextResponse.json({ error: 'No tenés acceso a esa sucursal' }, { status: 403 })
    }
  }
  const appointmentIds = await resolveScopedAppointmentIds({
    supabase,
    auth,
    companyId,
    branchId: branch_id,
  })

  if (appointmentIds.length === 0) {
    return NextResponse.json({
      payments: [],
      totals: { efectivo: 0, mercado_pago: 0, debito: 0, transferencia: 0, total: 0 },
    })
  }

  let query = supabase
    .from('payments')
    .select(`
      id, amount, method, receipt_number, created_at,
      appointment:appointments(
        id, date, start_time, branch_id, barber_id, service_price,
        client:clients(first_name, last_name),
        barber:barbers(id, name),
        service:services(name, price),
        branch:branches(name)
      )
    `)
    .order('created_at', { ascending: false })
    .limit(500)

  if (companyId) query = query.eq('company_id', companyId)
  query = query.in('appointment_id', appointmentIds)
  if (date_from) query = query.gte('created_at', date_from)
  if (date_to)   query = query.lte('created_at', date_to.includes('T') ? date_to : date_to + 'T23:59:59')

  const { data, error } = await query
  if (error) return NextResponse.json({ error: error.message }, { status: 500 })
  const visiblePayments = data ?? []

  const totals = {
    efectivo:      visiblePayments.filter((p: any) => p.method === 'efectivo').reduce((s: number, p: any) => s + Number(p.amount), 0),
    mercado_pago:  visiblePayments.filter((p: any) => p.method === 'mercado_pago').reduce((s: number, p: any) => s + Number(p.amount), 0),
    debito:        visiblePayments.filter((p: any) => p.method === 'debito').reduce((s: number, p: any) => s + Number(p.amount), 0),
    transferencia: visiblePayments.filter((p: any) => p.method === 'transferencia').reduce((s: number, p: any) => s + Number(p.amount), 0),
    total:         visiblePayments.reduce((s: number, p: any) => s + Number(p.amount), 0),
  }

  return NextResponse.json({ payments: visiblePayments, totals })
}
