import { NextRequest, NextResponse } from 'next/server'
import { createSupabaseAdmin } from '@/lib/supabase'
import { requireAuth, requirePermission, unauthorizedResponse } from '@/lib/api-auth'

export async function POST(req: NextRequest) {
  const auth = await requireAuth(req)
  if (!auth) return unauthorizedResponse()
  const denied = requirePermission(auth, 'edit_caja')
  if (denied) return denied

  const body = await req.json()
  const { appointment_id, amount, method, notes } = body

  if (!appointment_id || !amount || !method) {
    return NextResponse.json({ error: 'Faltan datos del pago' }, { status: 400 })
  }

  const validMethods = ['efectivo', 'mercado_pago', 'debito', 'transferencia']
  if (!validMethods.includes(method)) {
    return NextResponse.json({ error: 'Método de pago inválido' }, { status: 400 })
  }

  const supabase = createSupabaseAdmin()
  const { data: appointment } = await supabase
    .from('appointments')
    .select('id, barber_id, branch_id')
    .eq('id', appointment_id)
    .maybeSingle()

  if (!appointment) {
    return NextResponse.json({ error: 'Turno no encontrado' }, { status: 404 })
  }

  if (auth.role === 'barber') {
    const branchAllowed = !appointment.branch_id || auth.branch_ids.includes(appointment.branch_id)
    const ownsAppointment = appointment.barber_id === auth.barber_id

    if (!branchAllowed && !ownsAppointment) {
      return NextResponse.json({ error: 'No tenés permisos para registrar este cobro' }, { status: 403 })
    }
  }

  const { data: existingPayment } = await supabase
    .from('payments')
    .select('id, amount, method, receipt_number')
    .eq('appointment_id', appointment_id)
    .maybeSingle()

  if (existingPayment) {
    return NextResponse.json({ payment: existingPayment })
  }

  // Create payment (receipt_number auto-generated by DB trigger)
  const { data, error } = await supabase
    .from('payments')
    .insert({ appointment_id, amount: Number(amount), method, notes: notes ?? null, created_by: auth.session.user.id })
    .select('*')
    .single()

  if (error) return NextResponse.json({ error: error.message }, { status: 500 })

  // Mark appointment as completed only after the payment exists.
  const { error: apptError } = await supabase
    .from('appointments')
    .update({ status: 'completada' })
    .eq('id', appointment_id)

  if (apptError) {
    return NextResponse.json({ error: apptError.message }, { status: 500 })
  }

  return NextResponse.json({ payment: data })
}

export async function GET(req: NextRequest) {
  const auth = await requireAuth(req)
  if (!auth) return unauthorizedResponse()
  const denied = requirePermission(auth, 'view_caja')
  if (denied) return denied

  const { searchParams } = new URL(req.url)
  const branch_id  = searchParams.get('branch_id')
  const date_from  = searchParams.get('date_from')
  const date_to    = searchParams.get('date_to')

  const supabase = createSupabaseAdmin()

  let query = supabase
    .from('payments')
    .select(`
      *,
      appointment:appointments(
        id, date, start_time, branch_id,
        client:clients(first_name, last_name),
        barber:barbers(id, name),
        service:services(name, price),
        branch:branches(name)
      )
    `)
    .order('created_at', { ascending: false })

  if (date_from) query = query.gte('created_at', date_from)
  if (date_to)   query = query.lte('created_at', date_to.includes('T') ? date_to : date_to + 'T23:59:59')
  if (branch_id) query = query.eq('appointment.branch_id', branch_id)

  const { data, error } = await query
  if (error) return NextResponse.json({ error: error.message }, { status: 500 })

  // Filter by branch if needed (post-filter due to join)
  const filtered = branch_id
    ? (data ?? []).filter((p: any) => p.appointment?.branch_id === branch_id)
    : data ?? []

  const visiblePayments = auth.role === 'barber'
    ? filtered.filter((payment: any) => {
        const appointmentBranchId = payment.appointment?.branch_id
        const appointmentBarberId = payment.appointment?.barber?.id
        return (
          (appointmentBranchId && auth.branch_ids.includes(appointmentBranchId)) ||
          (auth.barber_id && appointmentBarberId === auth.barber_id)
        )
      })
    : filtered

  const totals = {
    efectivo:      visiblePayments.filter((p: any) => p.method === 'efectivo').reduce((s: number, p: any) => s + Number(p.amount), 0),
    mercado_pago:  visiblePayments.filter((p: any) => p.method === 'mercado_pago').reduce((s: number, p: any) => s + Number(p.amount), 0),
    debito:        visiblePayments.filter((p: any) => p.method === 'debito').reduce((s: number, p: any) => s + Number(p.amount), 0),
    transferencia: visiblePayments.filter((p: any) => p.method === 'transferencia').reduce((s: number, p: any) => s + Number(p.amount), 0),
    total:         visiblePayments.reduce((s: number, p: any) => s + Number(p.amount), 0),
  }

  return NextResponse.json({ payments: visiblePayments, totals })
}
